### ISSUE TITLE
dzen2 not compiled with Xinerama support

### ISSUE THREAD

**Issue by b0o** [goto-bus-stop/dzen2-bin#2]
Currently, this package doesn't compile dzen2 with Xinerama support. 

This package seemingly exists primarily to support [`goto-bus-stop/dzen2`](/goto-bus-stop/dzen2), which has support for Xinerama.

However, attempting to use the Xinerama `screen` option in the `goto-bus-stop/dzen2` package results in an error using a binary built with this package.

**Comment by goto-bus-stop** [comment]
oh yeah, i only needed xft back then, but figure it doesn't hurt to enable all dzen's options. i imagine mostly everyone with an X server has these things available. and if not it can be changed later to enable options based on what's available, and expose constants on the module so folks can check for features at runtime in node.

thanks! :package: 1.1.0 compiles xinerama and xpm support
